INSERT INTO CUSTOMER(NAME,SURNAME)values('Leonardo','DaVinci');
INSERT INTO CUSTOMER(NAME,SURNAME)values('Albert','Einstein');
INSERT INTO CUSTOMER(NAME,SURNAME)values('Nikola','Tesla');
INSERT INTO CUSTOMER(NAME,SURNAME)values('Isaac','Peral');