/*DROP TABLE IF EXISTS CUSTOMER;*/

CREATE TABLE CUSTOMER (
	ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(9)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

