/*DROP TABLE IF EXISTS CUSTOMER;*/

CREATE TABLE CUSTOMER (
	ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*
CREATE TABLE `expense` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item` varchar(45) NOT NULL,
  `amount` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
*/